### ISSUE TITLE
Doesn't load on Debian testing

### ISSUE THREAD

**Issue by tatuylonen** [aguinet/dragonffi#22]
Installed pydffi with "pip3 install pydffi" on Debian testing.  Seems to be version 0.4.0.  Trying to "import pydffi" gives error with Python 3.7.3.  I have also installed llvm-dev Debian package (seems to be version 1:7.0-47.1) and llvm (version 1:7.0-47.1).  I have also installed llvmlite 0.28.0 with pip3.

~/p/ec/testing>python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydffi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /j/home/ylo/.local/lib/python3.7/site-packages/pydffi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN4llvm32createAggressiveInstCombinerPassEv
>>>

**Comment by aguinet** [comment]
Related to #23. Currently fixing!

**Comment by aguinet** [comment]
See #23. That should be fine now. Please reopen if that's not the case!
