### ISSUE TITLE
_ZN4llvm32createAggressiveInstCombinerPassEv

### ISSUE THREAD

**Issue by Sarah114** [aguinet/dragonffi#23]
Traceback (most recent call last):
  File "<pyshell#269>", line 1, in <module>
    import pydffi
ImportError: /opt/intelpython3/lib/python3.6/site-packages/pydffi.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN4llvm32createAggressiveInstCombinerPassEv

I am not sure where to go with this. Does anyone know where I might start ... ?

**Comment by aguinet** [comment]
It looks like I broke the last build. I just rebased everything on llvm8 and generate new packages. It should fix this issue!

**Comment by aguinet** [comment]
dragonffi 0.5.0 is currently being uploaded on pypi. That should fix this issue! Please reopen if that's not the case.
