### ISSUE TITLE
Accessing fields in unnamed unions / structures (Microsoft)

### ISSUE THREAD

**Issue by neitsa** [aguinet/dragonffi#26]
Hi Adrien :)

I'm really enjoying doing things with dragonffi on Windows. I have hit a roadblock and don't know exactly how to deal with it (although I did find a way to circumvent the problem).

# Intro

I'm calling the [`NtQuerySystemInformation`](https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntquerysysteminformation) function with the undocumented `SystemBigPoolInformation` InfoClass  (0x42).

The call looks like this:

```python
r = ffi.NtQuerySystemInformation(
    0x42,  # info class
    pbuffer,  # output buffer
    0x1000,  # size of the output buffer
    pout)  # returned size
```

The structure returned by the API is a `SYSTEM_BIGPOOL_INFORMATION` and it looks like this:

```c
typedef struct _SYSTEM_BIGPOOL_ENTRY 
{
	union {
		PVOID VirtualAddress;
		ULONG_PTR NonPaged : 1;
	};
	ULONG_PTR SizeInBytes;
	union {
		UCHAR Tag[4];
		ULONG TagUlong;
	};
} SYSTEM_BIGPOOL_ENTRY, *PSYSTEM_BIGPOOL_ENTRY;

typedef struct _SYSTEM_BIGPOOL_INFORMATION {
	ULONG Count;
	SYSTEM_BIGPOOL_ENTRY AllocatedInfo[ANYSIZE_ARRAY];
} SYSTEM_BIGPOOL_INFORMATION, *PSYSTEM_BIGPOOL_INFORMATION;
```
The `Count` field tells how much `SYSTEM_BIGPOOL_ENTRY` there are in the `AllocatedInfo` field. So far, so good in python:

```python
    # cast pointer to buffer to _SYSTEM_BIGPOOL_INFORMATION pointer 
    sbi = pydffi.cast(pydffi.ptr(buffer), ffi.types.PSYSTEM_BIGPOOL_INFORMATION)
    print("SYSTEM_BIGPOOL_INFORMATION count: {0} ({0:#x})".format(sbi.obj.Count))

    # get the allocated info array
    allocated_info = sbi.obj.AllocatedInfo
```

# Problem

Now I can't access any of the **unnamed** unions field in the `SYSTEM_BIGPOOL_ENTRY` structure:

```python
    # doesn't work...
    print(f"SYSTEM_BIGPOOL_INFORMATION: {allocated_info[0].VirtualAddress.value:#x}")
    print(f"SYSTEM_BIGPOOL_INFORMATION: {allocated_info[1].VirtualAddress.value:#x}")
    print(f"SYSTEM_BIGPOOL_INFORMATION: {allocated_info[2].VirtualAddress.value:#x}")
```

# Workaround

If I change the structure to have **named** unions it does work without any problems:

C:
```c
    typedef struct _SYSTEM_BIGPOOL_ENTRY 
    {
        union {
            PVOID VirtualAddress;
            ULONG_PTR NonPaged : 1;
        }a;  // name
        ULONG_PTR SizeInBytes;
        union {
            UCHAR Tag[4];
            ULONG TagUlong;
        }b;  // name
    } SYSTEM_BIGPOOL_ENTRY, *PSYSTEM_BIGPOOL_ENTRY;
```

python:
```python
    print(f"allocated_info[0].VA: {allocated_info[0].a.VirtualAddress.value:#x}")
    print(f"allocated_info[1].VA: {allocated_info[1].a.VirtualAddress.value:#x}")
    print(f"allocated_info[2].VA: {allocated_info[2].a.VirtualAddress.value:#x}")
```

# Question

Is there any way to deal with unnamed unions / structures or do I explicitly have to name them (I guess unnamed union / structures is a MS extension?)

Thanks a lot!

**Comment by neitsa** [comment]
Thanks a lot for your answer Adrien :+1: :)

Would something like appending an auto-generated name would be a possible workaround for you if injecting the members into the containing struct / union is too much of hassle?

e.g:

```c
typedef struct {
    union { 
         int a; 
         short b; 
    }u1;  // auto-name
    struct { 
       int e; 
       short f; 
    }u2; // auto name
    int c; 
} Toto;
```

I guess this could also be recursive (i.e if `u1` contains an unnamed struct / union, auto-name it to `u11` or something like that). That **could** do the tricks.

**Comment by aguinet** [comment]
I thought about this. That might be the easy hack i'll implement.

I don't like it though because the user has to guess which auto generated name maps to which anonymous members. Moreover, if for instance the structure changes over time, names can change and that becomes a mess :)

**Comment by neitsa** [comment]
> the user has to guess which auto generated name maps to which anonymous members.

Yeah :smile: You're definitely right! I can name some structures like this from Windows which contains some deep anonymous structs / unions nesting... In the meantime I'll stick with naming them and will see if you happen to have a solution at some point. I'm not in hurry though, take your time!

Thanks a lot for your prompt answers!

**Comment by aguinet** [comment]
This should be properly fixed here: https://github.com/aguinet/dragonffi/pull/27 .

Let's see what Travis has to say :)

**Comment by aguinet** [comment]
Fixed merged in master ;)
