### ISSUE TITLE
Wheel pip for Python 3.8

### ISSUE THREAD

**Issue by RobinDavid** [aguinet/dragonffi#36]
I can't install dragonffi with Python 3.8. It does not seems to contain a wheel for python 3.8: https://pypi.org/project/pydffi/#files
_(using pip 20.1.1)_

Is it possible to create one ?

**Comment by aguinet** [comment]
Wheel for py3.8/linux_x64 has been uploaded to pypi! I also uploaded the sources, so that building from sources also works :) (providing an llvm installation)

**Comment by RobinDavid** [comment]
Yayee :partying_face: 
Thanks!
