### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error', on Debian bullseye/sid (ppc64)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [aguinet/dragonffi#56]
Hi.
I wasn't able to run one of the tests, on ppc64 (Qemu).

> oceanfish81@debian:~/dragonffi/release/tests$ ./includes
> terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_M_construct null not valid
> Aborted

Here is my environment:

> $ uname -a
> Linux debian 5.9.0-1-powerpc64 #1 SMP Debian 5.9.1-1 (2020-10-17) ppc64 GNU/Linux

> $ cat /proc/cpuinfo
> processor       : 0
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 1
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 2
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 3
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 4
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 5
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 6
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> processor       : 7
> cpu             : POWER7 (architected), altivec supported
> clock           : 1000.000000MHz
> revision        : 2.3 (pvr 003f 0203)
> 
> timebase        : 512000000
> platform        : pSeries
> model           : IBM pSeries (emulated by qemu)
> machine         : CHRP IBM pSeries (emulated by qemu)
> MMU             : Hash
> 

> $ cat /etc/cloud-release
> ID="genericcloud"
> VERSION="202010221749"

> $ cat /etc/os-release
> PRETTY_NAME="Debian GNU/Linux bullseye/sid"
> NAME="Debian GNU/Linux"
> ID=debian

I am running Qemu in such a way:

> qemu-system-ppc64w -smp 8 -hda ppc64_deb_cloud.vmdk -netdev tap,id=mynet0,ifname=tap1 -device e1000,netdev=mynet0 -machine pseries-2.7 -m 4G

> qemu-system-ppc64 --version
> QEMU emulator version 5.1.92 (v5.2.0-rc2-11843-gf571c4ffb5-dirty)
> Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

**Comment by advancedwebdeveloper** [comment]
The cloud image was taken from https://wolke.linn.io/s/rNF4jYjS3JQDBLt .
@JoelLinn provided it

**Comment by advancedwebdeveloper** [comment]
I have compressed my build folder https://github.com/advancedwebdeveloper/dragonffi_ppc64/raw/master/dragonffi_release.zip
.
Files are available on Github directly https://github.com/advancedwebdeveloper/dragonffi_ppc64

**Comment by JoelLinn** [comment]
Did you try running the tests on https://openpower.ic.unicamp.br/minicloud/ ? Maybe i should regenerate the image anyway...

**Comment by aguinet** [comment]
Can you please put all the PPC64 related issues into one single ticket (like this one), with a meaningful title, like "Issues with ppc64"? Thanks!

**Comment by advancedwebdeveloper** [comment]
I will try

**Comment by aguinet** [comment]
Okay perfect thanks!
