### ISSUE TITLE
Segfault in dlopen test (ppc64)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [aguinet/dragonffi#57]
Hello.
Here is what I got:
> $./dlopen
> Segmentation fault
.
This came from the same build, which was explained in https://github.com/aguinet/dragonffi/issues/56

**Comment by aguinet** [comment]
Can you please put all the PPC64 related issues into one single ticket?

**Comment by aguinet** [comment]
Now in https://github.com/aguinet/dragonffi/issues/61
