### ISSUE TITLE
compile_error test can't be compiled, on ppc64: anon_cu_0.c:1:1: error: unknown type name 'this'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [aguinet/dragonffi#58]
Here is what I got:
> $ ./compile_error
> /__dffi_private/anon_cu_0.c:1:1: error: unknown type name 'this'
> this is not valid C code
> ^
> /__dffi_private/anon_cu_0.c:1:8: error: expected ';' after top level declarator
> this is not valid C code
>        ^
>        ;
> 
> /__dffi_private/anon_cu_1.c:1:1: error: unknown type name 'still'
> still invalide code
> ^
> /__dffi_private/anon_cu_1.c:1:15: error: expected ';' after top level declarator
> still invalide code
>               ^
>               ;
> 
.
Description of my environment could be obtained [here](https://github.com/aguinet/dragonffi/issues/56)

**Comment by aguinet** [comment]
Can you please put all the PPC64 related issues into one single ticket?

**Comment by advancedwebdeveloper** [comment]
Will try

**Comment by aguinet** [comment]
Now in https://github.com/aguinet/dragonffi/issues/61
